from __future__ import annotations

import logging
import math
from io import StringIO
from pathlib import Path
from typing import Any

import ezdxf
from ezdxf import path as ezdxf_path

from dxfwiz.schemas import GeometryFile, MachineFile
from dxfwiz.schemas.common import Point2D
from dxfwiz.schemas.job import (
    ContourOperation,
    DrillOperation,
    HelicalDrillOperation,
    JobFile,
    MoveOperation,
    Operation,
    PocketOperation,
)
from dxfwiz.toolpaths.drilling import drill_operation_to_toolpaths, helical_drill_operation_to_toolpaths
from dxfwiz.toolpaths.model import SourceArcSegment, SourceLineSegment, SourcePath, ToolpathPass, ToolpathPlan
from dxfwiz.toolpaths.moves import move_operation_to_toolpaths
from dxfwiz.toolpaths.operations import contour_operation_to_toolpaths
from dxfwiz.toolpaths.pocketing import pocket_operation_to_toolpaths
from dxfwiz.toolpaths.routing import route_passes_within_groups


logger = logging.getLogger(__name__)


def compile_toolpath_plan(
    job: JobFile,
    geometry: GeometryFile,
    machine: MachineFile,
    fixed_dxf: str | Path | None = None,
) -> ToolpathPlan:
    logger.info("Compiling neutral toolpath plan for %d operation(s)", len(job.operations))
    resolver = GeometryResolver(geometry=geometry, generated={entity.id: entity for entity in job.generated_entities}, fixed_dxf=fixed_dxf)
    tools = {tool.id: tool for tool in machine.tools}
    safe_z = machine.machine.clear_z
    passes: list[ToolpathPass] = []
    warnings: list[str] = []

    for operation in job.operations:
        tool = tools.get(getattr(operation, "tool", None))
        if isinstance(operation, MoveOperation):
            passes.extend(move_operation_to_toolpaths(operation))
            continue
        if tool is None:
            warnings.append(f"{operation.id}: tool {operation.tool} is not defined in machine.yaml")
            continue
        try:
            operation_passes = _operation_to_passes(operation, resolver, tool, safe_z)
        except Exception as exc:
            logger.exception("Failed to compile operation %s", operation.id)
            warnings.append(f"{operation.id}: toolpath compilation failed: {exc}")
            continue
        passes.extend(operation_passes)
        for toolpath_pass in operation_passes:
            warnings.extend(toolpath_pass.warnings)

    routed_passes = route_passes_within_groups(
        passes=passes,
        operation_groups=job.operation_groups,
        safe_z=safe_z,
        operation_sort=machine.machine.operation_sort,
        role_by_operation={operation.id: _operation_role(operation) for operation in job.operations},
        nest_order_by_operation=_nest_order_by_operation(job, geometry),
    )
    routed_passes = _decorate_passes(
        passes=routed_passes,
        job=job,
        tools=tools,
        safe_z=safe_z,
    )

    return ToolpathPlan(
        units=job.units.length,
        coordinate_system=job.coordinate_system,
        commands=[
            {"type": "comment", "text": f"Generated by DXF Wizard for {job.job.name}"},
            {"type": "units", "length": job.units.length},
            {"type": "distance_mode", "mode": "absolute"},
            {"type": "plane", "plane": "xy"},
            {"type": "feed_mode", "mode": "units_per_min"},
            {"type": "coordinate_system", "code": job.coordinate_system},
            {"type": "rapid", "z": safe_z},
        ],
        source_paths=resolver.resolved_paths(),
        passes=routed_passes,
        warnings=warnings,
    )


def _operation_to_passes(operation: Operation, resolver: "GeometryResolver", tool, safe_z: float) -> list[ToolpathPass]:
    if isinstance(operation, DrillOperation):
        center = resolver.center(operation.entity)
        if center is None:
            return [_warning_pass(operation, tool, f"{operation.id}: cannot find drill center for {operation.entity}")]
        return drill_operation_to_toolpaths(operation, center, tool, safe_z)
    if isinstance(operation, HelicalDrillOperation):
        center = resolver.center(operation.entity)
        diameter = operation.hole_diameter or resolver.diameter(operation.entity)
        if center is None or diameter is None:
            return [_warning_pass(operation, tool, f"{operation.id}: cannot find helical drill geometry for {operation.entity}")]
        return helical_drill_operation_to_toolpaths(operation, center, diameter, tool, safe_z)
    if isinstance(operation, ContourOperation):
        source_path = resolver.source_path(operation.entity)
        if source_path is None:
            return [_warning_pass(operation, tool, f"{operation.id}: contour entity {operation.entity} has no usable path")]
        return contour_operation_to_toolpaths(operation, source_path, tool, safe_z)
    if isinstance(operation, PocketOperation):
        source_path = resolver.source_path(operation.entity)
        if source_path is None:
            return [_warning_pass(operation, tool, f"{operation.id}: pocket entity {operation.entity} has no usable path")]
        return pocket_operation_to_toolpaths(operation, source_path, tool, safe_z)
    return [_warning_pass(operation, tool, f"{operation.id}: operation type {operation.type} is not implemented")]


def _decorate_passes(
    passes: list[ToolpathPass],
    job: JobFile,
    tools: dict[str, Any],
    safe_z: float,
) -> list[ToolpathPass]:
    operations = {operation.id: operation for operation in job.operations}
    decorated: list[ToolpathPass] = []
    current_tool: str | None = None
    for toolpath_pass in passes:
        prefix: list[dict[str, Any]] = []
        operation = operations.get(toolpath_pass.operation_id)
        description = operation.description if operation is not None else None
        prefix.append({"type": "comment", "text": f"{toolpath_pass.operation_id}: {description or toolpath_pass.kind}"})
        for warning in toolpath_pass.warnings:
            prefix.append({"type": "warning", "text": warning})
        if toolpath_pass.tool and toolpath_pass.tool != current_tool:
            tool = tools.get(toolpath_pass.tool)
            prefix.extend(
                [
                    {"type": "rapid", "z": safe_z},
                    {"type": "tool_change", "tool": toolpath_pass.tool},
                ]
            )
            if tool is not None:
                rpm = getattr(operation, "spindle_speed", None) if operation is not None else None
                prefix.append({"type": "spindle_speed", "rpm": rpm or tool.speed})
            prefix.append({"type": "spindle", "state": "on"})
            current_tool = toolpath_pass.tool
        decorated.append(_copy_pass_with_moves(toolpath_pass, [*prefix, *toolpath_pass.moves]))
    if decorated:
        last = decorated[-1]
        decorated[-1] = _copy_pass_with_moves(
            last,
            [
                *last.moves,
                {"type": "rapid", "z": safe_z},
                {"type": "spindle", "state": "off"},
                {"type": "program_end"},
            ],
        )
    return decorated


def _copy_pass_with_moves(toolpath_pass: ToolpathPass, moves: list[Any]) -> ToolpathPass:
    data = toolpath_pass.model_dump()
    data["moves"] = moves
    return ToolpathPass.model_validate(data)


def _warning_pass(operation: Operation, tool, warning: str) -> ToolpathPass:
    return ToolpathPass(
        id=f"{operation.id}-warning",
        operation_id=operation.id,
        entity=getattr(operation, "entity", None),
        kind="move",
        tool=getattr(operation, "tool", None),
        tool_diameter=getattr(tool, "diameter", None),
        feed_rate=getattr(operation, "feed_rate", None) or getattr(tool, "feed_rate", None),
        z_top=0.0,
        z_bottom=0.0,
        warnings=[warning],
    )


def _operation_role(operation: Operation) -> str:
    if operation.type in {"drill", "helical_drill"}:
        return "hole"
    if operation.type == "pocket":
        return "pocket"
    if operation.type == "contour":
        return "contour"
    return operation.type


def _nest_order_by_operation(job: JobFile, geometry: GeometryFile) -> dict[str, int]:
    nest_order_by_entity = _nest_order_by_entity(geometry)
    return {
        operation.id: nest_order_by_entity.get(operation.entity, _fallback_operation_nest_order(operation))
        for operation in job.operations
        if hasattr(operation, "entity")
    }


def _nest_order_by_entity(geometry: GeometryFile) -> dict[str, int]:
    result: dict[str, int] = {}

    def visit(nodes, depth: int) -> None:
        for node in nodes:
            if node.role != "frame":
                result[node.entity] = max(0, 10 - depth)
            visit(node.children, depth + 1)

    visit(geometry.entity_map, 0)
    return result


def _fallback_operation_nest_order(operation: Operation) -> int:
    if operation.type in {"drill", "helical_drill"}:
        return 0
    if operation.type == "pocket":
        return 1
    if operation.type == "contour":
        return 2
    return 1


class GeometryResolver:
    def __init__(self, geometry: GeometryFile, generated: dict[str, Any], fixed_dxf: str | Path | None) -> None:
        self.geometry = geometry
        self.generated = generated
        self.entities = {entity.id: entity for entity in geometry.entities}
        self.dxf_lookup = _load_dxf_lookup(fixed_dxf)
        self._paths: dict[str, SourcePath] = {}

    def source_path(self, entity_id: str) -> SourcePath | None:
        if entity_id in self._paths:
            return self._paths[entity_id]
        entity = self.entities.get(entity_id) or self.generated.get(entity_id)
        if entity is None:
            return None
        source_path = self._source_path_from_entity(entity_id, entity)
        if source_path is not None:
            self._paths[entity_id] = source_path
        return source_path

    def center(self, entity_id: str) -> tuple[float, float] | None:
        entity = self.entities.get(entity_id) or self.generated.get(entity_id)
        if entity is None:
            return None
        center = getattr(entity, "center", None)
        if center is not None:
            return _point_xy(center)
        box = getattr(entity, "bounding_box", None)
        if box is not None:
            return (box.min.x + box.max.x) / 2, (box.min.y + box.max.y) / 2
        lower_left = getattr(entity, "lower_left", None)
        upper_right = getattr(entity, "upper_right", None)
        if lower_left is not None and upper_right is not None:
            ll = _point_xy(lower_left)
            ur = _point_xy(upper_right)
            return (ll[0] + ur[0]) / 2, (ll[1] + ur[1]) / 2
        return None

    def diameter(self, entity_id: str) -> float | None:
        entity = self.entities.get(entity_id) or self.generated.get(entity_id)
        return None if entity is None else getattr(entity, "diameter", None)

    def resolved_paths(self) -> list[SourcePath]:
        return list(self._paths.values())

    def _source_path_from_entity(self, entity_id: str, entity) -> SourcePath | None:
        if getattr(entity, "shape", None) == "circle" and getattr(entity, "center", None) and getattr(entity, "diameter", None):
            return _circle_source_path(entity_id, entity.center, entity.diameter, getattr(entity, "source_refs", []))
        if getattr(entity, "shape", None) == "rectangle" and getattr(entity, "lower_left", None) and getattr(entity, "upper_right", None):
            return _rectangle_source_path(entity_id, entity.lower_left, entity.upper_right, getattr(entity, "source_refs", []))
        for ref in getattr(entity, "source_refs", []):
            if ref.kind != "dxf_handle":
                continue
            dxf_entity = self.dxf_lookup.get(ref.value)
            if dxf_entity is not None:
                source_path = _dxf_source_path(entity_id, dxf_entity, [ref], self.geometry.units.coordinate_scale)
                if source_path is not None:
                    return source_path
        box = getattr(entity, "bounding_box", None)
        if box is not None:
            return _rectangle_source_path(entity_id, box.min, box.max, getattr(entity, "source_refs", []))
        return None


def _circle_source_path(entity_id: str, center, diameter: float, refs) -> SourcePath:
    cx, cy = _point_xy(center)
    radius = diameter / 2
    start = Point2D(x=cx + radius, y=cy)
    center_point = Point2D(x=cx, y=cy)
    return SourcePath(
        id=f"path-{entity_id}",
        entity=entity_id,
        closed=True,
        segments=[
            SourceArcSegment(
                type="arc",
                start=start,
                end=start,
                center=center_point,
                radius=radius,
                direction="ccw",
            )
        ],
        source_refs=list(refs),
    )


def _rectangle_source_path(entity_id: str, lower_left, upper_right, refs) -> SourcePath:
    min_x, min_y = _point_xy(lower_left)
    max_x, max_y = _point_xy(upper_right)
    points = [
        Point2D(x=min_x, y=min_y),
        Point2D(x=max_x, y=min_y),
        Point2D(x=max_x, y=max_y),
        Point2D(x=min_x, y=max_y),
    ]
    return _source_path_from_points(entity_id, points, list(refs), closed=True)


def _dxf_source_path(entity_id: str, dxf_entity, refs, scale: float) -> SourcePath | None:
    if dxf_entity.dxftype() == "CIRCLE":
        center = dxf_entity.dxf.center
        return _circle_source_path(
            entity_id,
            Point2D(x=float(center.x) * scale, y=float(center.y) * scale),
            float(dxf_entity.dxf.radius) * 2 * scale,
            refs,
        )
    try:
        points = [
            Point2D(x=float(vertex.x) * scale, y=float(vertex.y) * scale)
            for vertex in ezdxf_path.make_path(dxf_entity).flattening(0.005 / max(scale, 1e-9))
        ]
    except Exception:
        logger.exception("Failed to resolve DXF entity %s into a source path", entity_id)
        return None
    if len(points) < 2:
        return None
    closed = _same_point(points[0], points[-1])
    if closed:
        points = points[:-1]
    return _source_path_from_points(entity_id, points, list(refs), closed=closed)


def _source_path_from_points(entity_id: str, points: list[Point2D], refs, closed: bool) -> SourcePath:
    segments = []
    end_index = len(points) if closed else len(points) - 1
    for index in range(end_index):
        start = points[index]
        end = points[(index + 1) % len(points)]
        segments.append(SourceLineSegment(type="line", start=start, end=end))
    return SourcePath(
        id=f"path-{entity_id}",
        entity=entity_id,
        closed=closed,
        segments=segments,
        source_refs=list(refs),
    )


def _load_dxf_lookup(fixed_dxf: str | Path | None) -> dict[str, Any]:
    if fixed_dxf is None:
        return {}
    try:
        if isinstance(fixed_dxf, Path):
            doc = ezdxf.readfile(fixed_dxf)
        elif "\n" in fixed_dxf or fixed_dxf.lstrip().startswith("0"):
            doc = ezdxf.read(StringIO(fixed_dxf))
        else:
            doc = ezdxf.readfile(fixed_dxf)
    except Exception:
        logger.exception("Failed to load fixed DXF for toolpath geometry")
        return {}
    return {entity.dxf.handle: entity for entity in doc.modelspace()}


def _point_xy(point) -> tuple[float, float]:
    if isinstance(point, dict):
        return float(point["x"]), float(point["y"])
    return float(point.x), float(point.y)


def _same_point(first: Point2D, second: Point2D) -> bool:
    return math.hypot(first.x - second.x, first.y - second.y) <= 1e-9
