from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field
from io import StringIO
from pathlib import Path
from typing import Any, Literal

import ezdxf
from ezdxf import path
from shapely.geometry import LinearRing, Polygon

from dxfwiz.schemas import GeometryFile, MachineFile
from dxfwiz.schemas.job import ContourOperation, DrillOperation, HelicalDrillOperation, JobFile, Operation


logger = logging.getLogger(__name__)

CommandName = Literal[
    "comment",
    "units",
    "distance_mode",
    "plane",
    "feed_mode",
    "coordinate_system",
    "tool_change",
    "spindle_on",
    "spindle_off",
    "rapid",
    "feed",
    "arc",
    "dwell",
    "program_end",
]


@dataclass(frozen=True)
class ToolpathCommand:
    name: CommandName
    values: dict[str, Any] = field(default_factory=dict)


@dataclass
class ToolpathProgram:
    commands: list[ToolpathCommand] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def add(self, name: CommandName, **values: Any) -> None:
        self.commands.append(ToolpathCommand(name=name, values=values))

    def warn(self, message: str) -> None:
        logger.warning(message)
        self.warnings.append(message)
        self.add("comment", text=f"WARNING: {message}")


def build_toolpath_program(
    job: JobFile,
    geometry: GeometryFile,
    machine: MachineFile,
    fixed_dxf: str | Path | None = None,
) -> ToolpathProgram:
    logger.info("Building neutral toolpath program for %d operation(s)", len(job.operations))
    program = ToolpathProgram()
    dxf_lookup = _load_dxf_lookup(fixed_dxf)
    tools = {tool.id: tool for tool in machine.tools}
    entities = {entity.id: entity for entity in geometry.entities}
    generated = {entity.id: entity for entity in job.generated_entities}
    safe_z = machine.machine.clear_z

    program.add("comment", text=f"Generated by DXF Wizard for {job.job.name}")
    program.add("units", length=job.units.length)
    program.add("distance_mode", mode="absolute")
    program.add("plane", plane="xy")
    program.add("feed_mode", mode="units_per_min")
    program.add("coordinate_system", code=job.coordinate_system)
    program.add("rapid", z=safe_z)

    current_tool_id: str | None = None
    for operation in job.operations:
        tool = tools.get(operation.tool)
        if tool is None:
            program.warn(f"{operation.id}: tool {operation.tool} is not defined in machine.yaml")
            continue
        if operation.tool != current_tool_id:
            program.add("tool_change", tool=operation.tool)
            program.add("spindle_on", rpm=tool.speed)
            current_tool_id = operation.tool
        program.add("comment", text=f"{operation.id}: {operation.description or operation.type}")
        program.add("rapid", z=safe_z)
        if operation.type == "drill":
            _emit_peck_drill(program, operation, geometry, generated, safe_z, tool)
        elif operation.type == "helical_drill":
            _emit_helical_drill(program, operation, geometry, generated, safe_z, tool)
        elif operation.type == "contour":
            _emit_contour(program, operation, entities, dxf_lookup, safe_z, tool)
        elif operation.type == "pocket":
            program.warn(f"{operation.id}: pocket toolpaths are not implemented in this first pass")
        else:
            program.warn(f"{operation.id}: operation type {operation.type} is not implemented")

    program.add("rapid", z=safe_z)
    program.add("spindle_off")
    program.add("program_end")
    return program


def _emit_peck_drill(program, operation: DrillOperation, geometry, generated, safe_z, tool) -> None:
    center = _operation_center(operation, geometry, generated)
    if center is None:
        program.warn(f"{operation.id}: cannot find drill center for {operation.entity}")
        return
    peck = operation.peck_depth or tool.depth_per_pass or tool.diameter
    retract = operation.retract_amount or min(safe_z, peck)
    feed = operation.plunge_rate or tool.plunge_rate
    target = -operation.depth
    program.add("rapid", x=center[0], y=center[1])
    program.add("rapid", z=safe_z)
    depth = -min(peck, operation.depth)
    while depth >= target - 1e-9:
        program.add("feed", z=max(depth, target), feed=feed)
        if operation.dwell_time:
            program.add("dwell", seconds=operation.dwell_time)
        if depth <= target:
            break
        program.add("rapid", z=min(safe_z, depth + retract))
        depth -= peck
    program.add("rapid", z=safe_z)


def _emit_helical_drill(program, operation: HelicalDrillOperation, geometry, generated, safe_z, tool) -> None:
    entity = _entity_by_id(geometry, generated, operation.entity)
    center = _operation_center(operation, geometry, generated)
    if center is None or entity is None:
        program.warn(f"{operation.id}: cannot find helical drill geometry for {operation.entity}")
        return
    hole_diameter = getattr(entity, "diameter", None) or tool.diameter
    radius = max((hole_diameter - tool.diameter) / 2, 0.0)
    if radius <= 1e-6:
        program.warn(f"{operation.id}: helical radius is zero, falling back to peck drilling")
        _emit_peck_drill(program, operation, geometry, generated, safe_z, tool)
        return
    pitch = operation.pitch or tool.depth_per_pass or min(tool.diameter, operation.depth)
    feed = operation.feed_rate or tool.feed_rate
    plunge = operation.plunge_rate or tool.plunge_rate
    x0 = center[0] + radius
    y0 = center[1]
    program.add("rapid", x=x0, y=y0)
    program.add("rapid", z=safe_z)
    program.add("feed", z=0.0, feed=plunge)
    depth = 0.0
    while depth > -operation.depth + 1e-9:
        depth = max(depth - pitch, -operation.depth)
        program.add("arc", direction="ccw", x=x0, y=y0, z=depth, i=-radius, j=0.0, feed=feed)
    program.add("rapid", z=safe_z)


def _emit_contour(program, operation: ContourOperation, entities, dxf_lookup, safe_z, tool) -> None:
    entity = entities.get(operation.entity)
    if entity is None:
        program.warn(f"{operation.id}: contour entity {operation.entity} is not in geom.yaml")
        return
    points = _entity_points(entity, dxf_lookup)
    if len(points) < 3:
        program.warn(f"{operation.id}: contour entity {operation.entity} has no usable path")
        return
    total_depth = operation.depth + operation.extra_depth
    passes = _depth_passes(total_depth, operation.roughing.depth_per_pass)
    feed = operation.feed_rate or tool.feed_rate
    plunge = operation.plunge_rate or tool.plunge_rate
    if operation.tabs and operation.tabs.enabled:
        program.add("comment", text=f"{operation.id}: tabs are listed in op.yaml; tab lifting is not yet implemented")
    if operation.roughing.enabled:
        rough_points = _offset_operation_points(points, operation.offset, tool.diameter, operation.roughing.side_allowance)
        if len(rough_points) < 3:
            program.warn(f"{operation.id}: roughing offset failed for {operation.entity}")
            return
        for depth in passes:
            _emit_closed_path(program, rough_points, depth, safe_z, feed, plunge)
    if operation.finishing.enabled:
        finish_points = _offset_operation_points(points, operation.offset, tool.diameter, 0.0)
        if len(finish_points) < 3:
            program.warn(f"{operation.id}: finishing offset failed for {operation.entity}")
            return
        for _ in range(operation.finishing.passes):
            _emit_closed_path(program, finish_points, total_depth, safe_z, feed, plunge)
    program.add("rapid", z=safe_z)


def _offset_operation_points(
    points: list[tuple[float, float]],
    offset: str | None,
    diameter: float,
    side_allowance: float,
) -> list[tuple[float, float]]:
    amount = _offset_amount(offset, diameter, side_allowance)
    return _offset_closed_points(points, amount) if abs(amount) > 1e-9 else points


def _emit_closed_path(
    program: ToolpathProgram,
    points: list[tuple[float, float]],
    depth: float,
    safe_z: float,
    feed: float,
    plunge: float,
) -> None:
    start = points[0]
    program.add("rapid", x=start[0], y=start[1])
    program.add("rapid", z=safe_z)
    program.add("feed", z=-depth, feed=plunge)
    for x, y in points[1:]:
        program.add("feed", x=x, y=y, feed=feed)
    program.add("feed", x=start[0], y=start[1], feed=feed)


def _load_dxf_lookup(fixed_dxf: str | Path | None) -> dict[str, Any]:
    if fixed_dxf is None:
        return {}
    try:
        if isinstance(fixed_dxf, Path):
            doc = ezdxf.readfile(fixed_dxf)
        elif "\n" in fixed_dxf or fixed_dxf.lstrip().startswith("0"):
            doc = ezdxf.read(StringIO(fixed_dxf))
        else:
            doc = ezdxf.readfile(fixed_dxf)
    except Exception:
        logger.exception("Failed to load fixed DXF for toolpath geometry")
        return {}
    return {entity.dxf.handle: entity for entity in doc.modelspace()}


def _operation_center(operation, geometry, generated) -> tuple[float, float] | None:
    entity = _entity_by_id(geometry, generated, operation.entity)
    if entity is None:
        return None
    center = getattr(entity, "center", None)
    if center is not None:
        return _point_xy(center)
    box = getattr(entity, "bounding_box", None)
    if box is None:
        return None
    return (box.min.x + box.max.x) / 2, (box.min.y + box.max.y) / 2


def _entity_by_id(geometry, generated, entity_id: str):
    for entity in geometry.entities:
        if entity.id == entity_id:
            return entity
    return generated.get(entity_id)


def _point_xy(point) -> tuple[float, float]:
    if isinstance(point, dict):
        return float(point["x"]), float(point["y"])
    return float(point.x), float(point.y)


def _entity_points(entity, dxf_lookup) -> list[tuple[float, float]]:
    if entity.shape == "circle" and entity.center and entity.diameter:
        return _circle_points(entity.center.x, entity.center.y, entity.diameter / 2)
    for ref in entity.source_refs:
        if ref.kind != "dxf_handle":
            continue
        dxf_entity = dxf_lookup.get(ref.value)
        if dxf_entity is None:
            continue
        if dxf_entity.dxftype() == "CIRCLE":
            center = dxf_entity.dxf.center
            return _circle_points(float(center.x), float(center.y), float(dxf_entity.dxf.radius))
        if dxf_entity.dxftype() == "LWPOLYLINE":
            points = [
                (float(vertex.x), float(vertex.y))
                for vertex in path.make_path(dxf_entity).flattening(0.005)
            ]
            return points
    if entity.bounding_box:
        box = entity.bounding_box
        return [
            (box.min.x, box.min.y),
            (box.max.x, box.min.y),
            (box.max.x, box.max.y),
            (box.min.x, box.max.y),
        ]
    return []


def _circle_points(cx: float, cy: float, radius: float, segments: int = 96) -> list[tuple[float, float]]:
    return [
        (cx + math.cos(2 * math.pi * index / segments) * radius, cy + math.sin(2 * math.pi * index / segments) * radius)
        for index in range(segments)
    ]


def _offset_amount(offset: str | None, diameter: float, finishing_allowance: float) -> float:
    if offset == "outside":
        return diameter / 2 + finishing_allowance
    if offset == "inside":
        return -(diameter / 2 + finishing_allowance)
    return 0.0


def _offset_closed_points(points: list[tuple[float, float]], amount: float) -> list[tuple[float, float]]:
    ring = LinearRing(points)
    polygon = Polygon(ring)
    if not polygon.is_valid or polygon.area <= 0:
        polygon = polygon.buffer(0)
    offset = polygon.buffer(amount, join_style="mitre")
    if offset.is_empty:
        return []
    if offset.geom_type == "MultiPolygon":
        offset = max(offset.geoms, key=lambda item: item.area)
    return [(float(x), float(y)) for x, y in offset.exterior.coords[:-1]]


def _depth_passes(depth: float, step: float) -> list[float]:
    passes = []
    value = min(step, depth)
    while value < depth - 1e-9:
        passes.append(value)
        value += step
    passes.append(depth)
    return passes
